# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_auto_20230622_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='tracking_pixel',
        ),
        migrations.AddField(
            model_name='emailsubscriber',
            name='tracking_pixel',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
